ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ com.swart.api.ApplicationKt.module ]
    }
}

storage {
    jdbcUrl = ${?DB_JDBC_URL}
    dbUser = ${?DB_USER}
    dbPassword = ${?DB_PASSWORD}
}
